name: hacid-cs-kg
services:
  out-facing:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./data:/data
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  triplestore:
    image: ontotext/graphdb:11.0.1
    container_name: graphdb-hacid-cs
    ports:
    - '7200:7200'
  lodview:
    image: lodview
    container_name: lodview
    restart: unless-stopped
    ports:
    - '8080:8080'
    - '8009:8009'
  yasgui:
    image: mathiasvda/yasgui
    environment:
      YASGUI_DEFAULT_ENDPOINT: "https://keng.istc.cnr.it/hacid-cs-kg/sparql"
    ports:
    - '8088:8080'
